### ISSUE TITLE
Save/Load Progress

### ISSUE THREAD

**Issue by Phantom5800** [Phantom5800/pmr-tracker#12]
Add support for saving and loading the current state of the tracker. This would better support people that don't finish a seed all at once. Easiest method is via a serializable text file, probably better than bloating localstorage with hundreds of flags that few people would make use of?

**Comment by Phantom5800** [comment]
This has come up a few times now, bumping priority, but will need to figure out the best way to handle this.

**Comment by Xenophane12** [comment]
I cant make it load my save
