### ISSUE TITLE
Adjust spacing between Sections to be equal

### ISSUE THREAD

**Issue by Namaha23** [Phantom5800/pmr-tracker#21]
Small cosmetic issue, but right now there is a significant amount of extra space between the Required Items section and the Misc. Items section (at least compared to the amt of space between the Misc. Items and Misc. Keys section). This seems to only be noticeable when the browser window size is adjusted to force each section to appear in a single column. See screenshot: https://i.imgur.com/mX5ffci.png

**Comment by Phantom5800** [comment]
Related to #10. I'll leave it open since it can be fixed separately, but this is a much larger scope ticket that would also address this.
