### ISSUE TITLE
Missing Checks

### ISSUE THREAD

**Issue by TimEnchante** [Phantom5800/pmr-tracker#23]
The tracker is missing a couple checks that I've noticed, namely giving the doll to Goombario's sister and getting Kooper's shell from the fuzzies. I'll keep you updated on any more I may find.

**Comment by Phantom5800** [comment]
Items that only give star pieces won't be on the map tracker yet (such as Dolly and Dictionary). But I'll make a note to add them whenever those checks are randomized. The fuzzy minigame check has also been added! Thank you for reporting these.
