### ISSUE TITLE
Synchronize item tracker and map tracker checks

### ISSUE THREAD

**Issue by icebound777** [Phantom5800/pmr-tracker#26]
Currently, some checks have to be manually synch'd between the two trackers, like beating Anti-Guy.
Would be great if that were to happen automatically!

**Comment by Phantom5800** [comment]
Should be done with existing checks, Master was the hard one due to the functional difference on the key item tracker, but cursory testing looks good

**Comment by Phantom5800** [comment]
Reopening this ticket since I had to disable the feature for save/load because of some edge cases in the implementation (will fix this part eventually, but it's a lot lower priority than save/load state)

**Comment by Phantom5800** [comment]
With the current state of the tracker, there isn't actually anything to synchronize. All "checks" (other than rip cheato) exist in map tracker only, and rip cheato is not listed in the map tracker, but will likely be moved there at some point
