### ISSUE TITLE
missing checks

### ISSUE THREAD

**Issue by TimEnchante** [Phantom5800/pmr-tracker#28]
Rip Cheato in the TTT doesn't seem to have an entry in the tracker, and he is several checks (I think 11).

**Comment by icebound777** [comment]
Adding onto this issue, Flower Fields > Yellow Flower is missing the item in the flowers to the right of the tree.

**Comment by Phantom5800** [comment]
I'm gonna close this from the perspective of treating rip cheato like a shop. He's visually on the main tracker already and I'd rather not flood the map tracker with long lists like shop items unless I hear this from a lot of people.
