### ISSUE TITLE
Export/Import function for tracker progress

### ISSUE THREAD

**Issue by bowshockthe1st** [Phantom5800/pmr-tracker#30]
Since for some reason the tracker doesn't keep progress for me independent on browser used, I suppose a function to export the current tracker progress as .txt, and vice versa a function to import from the .txt would be a great QoL enhancement, also viable when switching between devices (yes I actually do that because I play rando on my work-issued device too lol)

**Comment by Phantom5800** [comment]
This was added recently with a json export/import
