### ISSUE TITLE
Reset Tracker button does not fully reset the map tracker

### ISSUE THREAD

**Issue by Namaha23** [Phantom5800/pmr-tracker#33]
Relates to https://github.com/Phantom5800/pmr-tracker/issues/32

Resetting the tracker has some weird behavior in the Map Tracker section. It seems to reset all of the map tiles to show that they have available checks, even if the setting allowing those checks (eg. Coinsanity) is disabled. Despite the map tiles being active, the checkboxes within cannot be interacted with unless the relevant option is enabled. One fix seems to be toggling Coinsanity and other relevant options on & off in the tracker's Seed Settings, which then sets these map tiles to their proper state

![screenshot shows 2 lit up map tiles in the Dry Dry Desert that are only relevant with panels/coins shuffled](https://i.imgur.com/1h5qfsk.png)

The other thing I noticed is that the Checkboxes do not seem to reset. Even though the map tile itself will reset and light up, anything that was checked off in that map tile remains checked off

**Comment by Phantom5800** [comment]
Fixed by https://github.com/Phantom5800/pmr-tracker/pull/34
