### ISSUE TITLE
Add a "Check all" button for each sub-area

### ISSUE THREAD

**Issue by dotzo** [Phantom5800/pmr-tracker#44]
Some areas have a lot of individual checks that are easily doable in 1 go as you go through the area. Clicking every single checkbox therefore can be a bit tedious.

A button or checkbox next to the area name header above the checklist to check all of the checkboxes in a single click.

**Comment by DustyDogCodex** [comment]
hi! I'd love to work on this issue if its still available!

**Comment by Phantom5800** [comment]
> hi! I'd love to work on this issue if its still available!

Go for it! I don't have a label for anything in progress, but it can be assumed that nothing is being actively worked on unless someone says something as far as I'm concerned.

**Comment by CoreParadox** [comment]
Hey! I added this feature, but it works by right clicking a map (not a region) to mark off all of it's checks

https://github.com/Phantom5800/pmr-tracker/pull/74
