### ISSUE TITLE
Rando Alpha 2 changes to tracker

### ISSUE THREAD

**Issue by icebound777** [Phantom5800/pmr-tracker#5]
Due to a few upcoming changes in the alpha 2 seeds, I suggest the following changes to the tracker:
* BlueHouseOpen removes the OddKey from the item pool: Remove OddKey from tracker if this is active (the same applies to FlowerGateOpen, but you already have a toggle for that)
* Anti Guy will logically require a LemonCandy. This means it will in total require access to Tayce T., the Cookbook, a Lemon and a CakeMix (however you'd like to show that on the tracker)
* The dojo's degree cards and diploma will be shuffled, turning the dojo into 5 checks. Since it is unlikely that a player will be able to beat Master 3 when they can beat Chan or Lee at first, a reminder on the tracker for dojo fights left could be useful

**Comment by Phantom5800** [comment]
Do the dojo fights still require the previous degree cards?

**Comment by Phantom5800** [comment]
I guess additionally, will the dojo will be a separate config setting?

**Comment by icebound777** [comment]
They won't require the previous degree card, and now that you mention it, the dojo should probably be a separate config setting. Don't want to force casual players to fight Master 3.

**Comment by Phantom5800** [comment]
Everything has been added, Anti guy logic right now is just a tooltip about lemon candy, maybe will come up with better ideas later.
![image](https://user-images.githubusercontent.com/3606472/150880313-6832baac-7257-4ff5-b573-bba9674e6ac6.png)
