### ISSUE TITLE
Missing check in Yoshi's Island SE Jungle?

### ISSUE THREAD

**Issue by WolfBoi008** [Phantom5800/pmr-tracker#59]
I hit the tree near the east exit of this room and it dropped a soda. This might be vanilla, but if it isn't, it's a missing check.

**Comment by Phantom5800** [comment]
The only tree in the jungle with an item drop is in the NW Jungle room

**Comment by WolfBoi008** [comment]
In the SE room, the one with a ? block and a Spear Guy on the island in the center (and west of the Sushie room), there was a tree with a soda in it.

**Comment by Phantom5800** [comment]
That's a bug in the randomizer then, because that tree has a coin in vanilla and it should be reported to the rando devs in discord.

**Comment by WolfBoi008** [comment]
I'm doing coinsanity, so shouldn't it still count for that?

**Comment by Phantom5800** [comment]
coinsanity is not supposed to add trees and bushes to the pool

**Comment by WolfBoi008** [comment]
Oh, gotcha! Sorry for the confusion!
