### ISSUE TITLE
Requirements for chapter 2 beatable seem off

### ISSUE THREAD

**Issue by icebound777** [Phantom5800/pmr-tracker#6]
Clicking
* Bombette
* Parakarry
* Pulsestone
* 4 RuinsKeys and
* 2 out of the three stones

marks Mamar as obtainable.
Is there a way I'm missing to reach Tutankoopa without all 3 stones or is there an oversight?

**Comment by Phantom5800** [comment]
Oops, yep that's a bug, can fix that pretty quick

**Comment by Phantom5800** [comment]
Fixed now, force reloading the public page should be correct
