### ISSUE TITLE
[Hammerless] Multiple incorrect spots

### ISSUE THREAD

**Issue by Polarthief** [Phantom5800/pmr-tracker#62]
I'm unsure on every single check regarding Hammerless, but there's a few that I noticed. The two major ones are regarding grounded blocks or trees that you need a Hammer (or Bombette) to break open/shake. Without either selected, the tracker incorrectly states I can do these checks.
In Shy Guy's Toybox, the spring boxes require Super Boots or a Hammer to use and are required to explore a few of the rooms, which the tracker is stating I can do (I can't). It also says I can do the color puzzle (Y>G>R>B) hammer-less too (Bombette also sadly doesn't work on either of these like she does with grounded blocks and trees).
Found another: Koopa Village => Fuzzy game. Can't hit those trees w/o a hammer either (even Bombette doesn't work).

**Comment by MarioManTAW** [comment]
Hammerless logic has not yet been implemented into the tracker. I might work on this (and some other logic issues) later today.
