### ISSUE TITLE
You can get the item on top of the brick block in the spin attack room with the super boots

### ISSUE THREAD

**Issue by sjl057** [Phantom5800/pmr-tracker#63]
[https://youtu.be/cP_0HyeIyeI](url)

**Comment by MarioManTAW** [comment]
How difficult would you say that jump is? Glitchless logic avoids including things that may be difficult or unintuitive for beginners even if they are possible glitchless.

**Comment by Phantom5800** [comment]
It's much easier than the invisible blocks in crystal palace. I wouldn't be opposed to including it, though I am unsure if the rando generation logic considers this a glitch or not (it probably does).

**Comment by Phantom5800** [comment]
This is now part of glitch logic in the randomizer, which at this time is something we will not be adding to the tracker.
