### ISSUE TITLE
Add toggle to allow right clicking region to mark only available checks

### ISSUE THREAD

**Issue by MythicFrog** [Phantom5800/pmr-tracker#79]
**Is your feature request related to a problem? Please describe.**
Right clicking a region clears all checks not only available checks

**Describe the solution you'd like**
When right clicking a region it should check off all available checks instead of all checks. This would allow fully checking everything you can in a region and simply right clicking at the end, prevents having to constantly click over in larger regions that require double dipping

**Additional context**
A user is discord suggested this and I'll be working on this as a toggle in the tracker settings (top-right). Just want to make sure this is something you want done before I start work.

**Comment by MarioManTAW** [comment]
I agree with this and would even suggest that that should be the default behavior, no need to add a toggle.

**Comment by MythicFrog** [comment]
When working on things I usually leave the current functionality as default and add toggles so users don't get surprised when things don't work the way they're used to but for sure if that how it should be implemented. I have the code running currently so I can finalize the branch whenever and send in a PR.

**Comment by Phantom5800** [comment]
Yeah, this would be reasonable to just have as default behavior instead of a feature toggle. Would like to keep toggles to much larger things and this wouldn't inherently change anything about the current behavior.

**Comment by Phantom5800** [comment]
The original commit btw 8e1f5211f3c3424b1350e5172763e219cfc571d4. Changing it to marking only the checks from currently enabled settings would make sense.

**Comment by MythicFrog** [comment]
In #75 I had already restricted it to only mark off checks that were not disabled since it was messing up the total checks count.

I have the basics of this issue already done on a branch so I'll just remove the toggle and submit a pr
