### ISSUE TITLE
Compact tracker breaks several item sections

### ISSUE THREAD

**Issue by icebound777** [Phantom5800/pmr-tracker#8]
After switching to the compact tracker, all sections except for "Required Items" have a chance to stop working.
They sometimes no longer accept clicks on most items in the other sections, and clicking counting checks increases them by more than 1 at a time.
The amount the counting checks increase per click seems to be related to the number of times one has turned off or on the compact tracker; so turning compact tracker on and off increases counters by 3 per click, turning compact tracker on again increases by 4 per click, turning it off again increases by 5 and so on.

(on Mozilla Firefox for Ubuntu 96.0 (64-bit) with AdBlock Plus plugin active)

**Comment by Phantom5800** [comment]
This was a testing oversight on my part with the misc. areas when adding the compact tracker. It should be fixed now.
