### ISSUE TITLE
Missing Check on Yoshi's Island

### ISSUE THREAD

**Issue by piefish1996** [Phantom5800/pmr-tracker#88]
There's a Bub-ulb in Sushi's Room on Yoshi's Island that wasn't included in the checks

**Comment by MarioManTAW** [comment]
That Bub-ulb does not give you an item. You instead receive the 4th Magical Seed from Kolorado after returning the Volcano Vase.

**Comment by piefish1996** [comment]
Shows you how long it's been since I've played the regular game lol
