### ISSUE TITLE
Missing Check In Yoshi's Island

### ISSUE THREAD

**Issue by okdanny97** [Phantom5800/pmr-tracker#96]
**Describe the bug**
SW Jungle in Yoshi's Island is missing a ? Block check (the spoiler log records it as "SW Jungle (Super Block) - In SuperBlock"
This is in the bottom right of the room.

**To Reproduce**
Prominent in any seed

**Expected behavior**
This check should be listed

**Screenshots**
![image](https://github.com/Phantom5800/pmr-tracker/assets/18012603/c1904fc2-3dea-4376-b35e-a0a8c8b053fa)

**Environment (please complete the following information):**

**Additional context**

**Comment by christianlegge** [comment]
This check is a Super Block, not a ? Block. It shows up when "Super Blocks Randomized" is on (or shows up greyed out when "Hide Non-Shuffled Checks" is off). Closing.
